spring:
  datasource:
    #    name: bsss
    #    url: jdbc:mysql://localhost:3306/bsss?serverTimezone=UTC
    #    username: root
    #    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: BSSS
    url: jdbc:mysql://localhost:3306/BSSS?serverTimezone=Asia/Shanghai&useSSL=FALSE&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Bsss1234!
#路径最后的/得加上，因为代码的路径是我字符串上加的
  resources:
    static-locations: classpath:/resource/, file:/root/BSSS/

avatarPath: /root/BSSS/avatar/