spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false
    database: mysql
  thymeleaf:
    cache: false
  jackson:
    time-zone: Hongkong
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
#  security:
#    user:
#      name: user
#      password: "000"
server:
  port: 8080
  servlet:
    context-path: /api

filepath: ./file/
avatarPath: ./root/avatar/

#mybatis:
#  mapper-locations: classpath:mapper/*.xml